import React from 'react';
import { FileText, Target, MessageSquare, Mic, PhoneCall, Video, Activity, Map, BarChart as BarChartIcon, LineChart as LineChartIcon, Trophy, Bot, UserCheck, Building, Lightbulb, PenTool, Globe, BrainCircuit, Briefcase, BookOpen, Cpu } from 'lucide-react';

export const COMPLETE_FEATURES = [
  { title: "AI Resume Builder", description: "Generate ATS-friendly resumes optimized for your target roles in seconds.", icon: <FileText className="w-6 h-6 text-accent" />, href: "/dashboard/session" },
  { title: "Resume vs Job Matcher", description: "Upload job descriptions to precisely map your skill gaps and missing keywords.", icon: <Target className="w-6 h-6 text-accent" />, href: "/dashboard/feature/resume-vs-job-matcher" },
  { title: "AI Interview Q&A Generator", description: "Generate custom tailored questions and expert model answers for any role.", icon: <MessageSquare className="w-6 h-6 text-accent" />, href: "/dashboard/feature/ai-interview-q-a-generator" },
  { title: "Mock Interview Simulator", description: "Experience genuine speaking pressure with highly realistic conversational AI.", icon: <Mic className="w-6 h-6 text-accent" />, href: "/dashboard/session" },
  { title: "Voice-Based Interview", description: "Conduct hands-free, conversational phone-screen style interviews seamlessly.", icon: <PhoneCall className="w-6 h-6 text-accent" />, href: "/dashboard/feature/voice-based-interview" },
  { title: "AI Video Interview Analyzer", description: "Real-time analysis of your facial expressions, posture, and eye contact.", icon: <Video className="w-6 h-6 text-accent" />, href: "/dashboard/feature/ai-video-interview-analyzer" },
  { title: "Real-Time Speaking Coach", description: "Get instant live feedback on your pacing, filler words, and vocal tone.", icon: <Activity className="w-6 h-6 text-accent" />, href: "/dashboard/feature/real-time-speaking-coach" },
  { title: "AI Career Path Architect", description: "Generate a timeline-based roadmap charting your optimal professional trajectory.", icon: <Map className="w-6 h-6 text-accent" />, href: "/dashboard/career" },
  { title: "Study Concepts & Roadmap", description: "Receive personalized technical study plans tailored to your exact timeline.", icon: <BookOpen className="w-6 h-6 text-accent" />, href: "/dashboard/study" },
  { title: "Skill Gap Analyzer", description: "Identify missing vital qualifications and discover resources to obtain them.", icon: <BarChartIcon className="w-6 h-6 text-accent" />, href: "/dashboard/feature/skill-gap-analyzer" },
  { title: "Performance Dashboard", description: "Track your weaknesses and get actionable progress visualizations weekly.", icon: <LineChartIcon className="w-6 h-6 text-accent" />, href: "/dashboard" },
  { title: "Gamification System", description: "Earn XP, maintain daily prep streaks, and unlock badges to stay motivated.", icon: <Trophy className="w-6 h-6 text-accent" />, href: "/dashboard/feature/gamification-system" },
  { title: "AI Career Assistant Chatbot", description: "Ask any career or interview question and get expert, contextual advice 24/7.", icon: <Bot className="w-6 h-6 text-accent" />, href: "/dashboard/feature/ai-career-assistant-chatbot" },
  { title: "AI Mentor Mode", description: "Get guided, step-by-step coaching for difficult algorithms and concepts.", icon: <UserCheck className="w-6 h-6 text-accent" />, href: "/dashboard/feature/ai-mentor-mode" },
  { title: "Company-Specific Interview Prep", description: "Practice with custom tailored questions asked by FAANG and top tech companies.", icon: <Building className="w-6 h-6 text-accent" />, href: "/dashboard/feature/company-specific-interview-prep" },
  { title: "AI Project Idea Generator", description: "Brainstorm unique, impressive side projects to add substantial weight to your portfolio.", icon: <Lightbulb className="w-6 h-6 text-accent" />, href: "/dashboard/feature/ai-project-idea-generator" },
  { title: "AI Cover Letter Generator", description: "Instantly draft highly compelling cover letters precisely tailored to the job description.", icon: <PenTool className="w-6 h-6 text-accent" />, href: "/dashboard/feature/ai-cover-letter-generator" },
  { title: "Multi-Language Support", description: "Practice your interviews comfortably in English, Hindi, Kannada, and more local dialects.", icon: <Globe className="w-6 h-6 text-accent" />, href: "/dashboard/feature/multi-language-support" },
  { title: "Smart Revision Mode", description: "Use intelligent spaced repetition and auto-generated AI flashcards for your weakest topics.", icon: <BrainCircuit className="w-6 h-6 text-accent" />, href: "/dashboard/feature/smart-revision-mode" },
  { title: "Recruiter Simulation Mode", description: "Experience tough, stress-inducing behavioral questions from a simulated hiring manager.", icon: <Briefcase className="w-6 h-6 text-accent" />, href: "/dashboard/feature/recruiter-simulation-mode" },
  { title: "Memory-Based Learning AI", description: "An adaptive AI that specifically remembers your past mistakes and adjusts its questions.", icon: <Cpu className="w-6 h-6 text-accent" />, href: "/dashboard/feature/memory-based-learning-ai" }
];
